# Schema:
# https://docs.python.org/3.5/library/logging.config.html#configuration-dictionary-schema
version: 1
disable_existing_loggers: false

root:
  level: NOTSET
  handlers: [rootFileHandler]

loggers:
  esok:
    level: DEBUG
    handlers: [infoFileHandler, warningFileHandler, errorFileHandler]
    propagate: true

handlers:
  infoFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: fileFormatter
    filters: [infoCap]
    filename: info.log  # Location of this file is determined by code
    maxBytes: 5000000
    backupCount: 1
    encoding: UTF-8
    delay: false
  warningFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: fileFormatter
    filters: [warningCap]
    filename: warning.log  # Location of this file is determined by code
    maxBytes: 5000000
    backupCount: 1
    encoding: UTF-8
    delay: false
  errorFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: fileFormatter
    filename: error.log  # Location of this file is determined by code
    maxBytes: 5000000
    backupCount: 1
    encoding: UTF-8
    delay: false
  rootFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: fileFormatter
    filename: all.log  # Location of this file is determined by code
    maxBytes: 5000000
    backupCount: 1
    encoding: UTF-8
    delay: false

filters:
  infoCap:
    (): esok.log.LogLevelFilter.LogLevelFilter
    level: INFO
  warningCap:
    (): esok.log.LogLevelFilter.LogLevelFilter
    level: WARNING

formatters:
  fileFormatter:
    format: '## %(asctime)s %(levelname)s %(name)s > %(message)s'
